"""Per-archetype social_vitality gain logic.

Two sources currently award social_vitality through this helper:

  - 'chat': simulation CHAT action (engine.py main action handler +
    contextual-CHAT bridge for non-CHAT actions).
  - 'post': NX POST autopost generated by run_feed_generation_tick.
    Only standalone posts award gain; replies don't.

The shop ('Team Lunch') and passive recovery write social_vitality
directly with their own caps (100 and 25 respectively) and don't go
through this helper — they're not chat/post-shaped.
"""

from __future__ import annotations

import logging
from typing import Literal

log = logging.getLogger("nx_engine")

# Per-archetype social_vitality gain when the dev produces a chat OR a
# feed post. Same table is reused across both sources by design — a
# DEGEN being more social than a LURKER is independent of whether they
# spoke aloud or posted in a feed. INFLUENCER tops the table; LURKER
# gains 0 because observing anonymously isn't really socializing.
SOCIAL_VITALITY_GAIN: dict[str, int] = {
    "INFLUENCER":    3,
    "DEGEN":         2,
    "FED":           2,
    "HACKTIVIST":    1,
    "10X_DEV":       1,
    "GRINDER":       1,
    "SCRIPT_KIDDIE": 1,
    "LURKER":        0,
}

# Cap on the chat/post route. social_vitality runs 0–100 in DB, but
# chat alone tops out at 40 by design — reaching the 40→100 band
# requires the shop ('Team Lunch') or successful raids. Posts share
# the same 40 cap so the two passive routes don't stack into a free
# path to max stat.
SOCIAL_VITALITY_CAP_CHAT_POST: int = 40

# Telemetry source tag. Kept as a Literal so a typo at the call site
# fails type-checks instead of silently mis-attributing gain in logs.
SocialGainSource = Literal["chat", "post", "shop", "passive"]


def _apply_social_vitality_gain(
    cur,
    dev_token_id: int,
    archetype: str,
    source: SocialGainSource,
) -> int:
    """Apply SOCIAL_VITALITY_GAIN honestly, respecting the 40 cap.

    Returns the EFFECTIVE gain — the amount that actually hit the DB.
    If the dev is already at cap, returns 0 so callers can surface an
    honest "+N SOCIAL" badge instead of lying about a gain that
    never persisted.

    Same cursor as the caller — runs inside the caller's transaction
    so a downstream failure rolls back the gain alongside the rest of
    the action.
    """
    raw = SOCIAL_VITALITY_GAIN.get(archetype, 1)
    if raw <= 0:
        return 0
    cur.execute(
        "SELECT social_vitality FROM devs WHERE token_id = %s",
        (dev_token_id,),
    )
    row = cur.fetchone()
    current = row["social_vitality"] if row else 0
    effective = max(0, min(raw, SOCIAL_VITALITY_CAP_CHAT_POST - current))
    if effective > 0:
        cur.execute(
            "UPDATE devs SET social_vitality = social_vitality + %s "
            "WHERE token_id = %s",
            (effective, dev_token_id),
        )
        log.info(
            "[social] gain dev=%s archetype=%s source=%s raw=%s effective=%s new=%s",
            dev_token_id, archetype, source, raw, effective, current + effective,
        )
    return effective
