import { useState, useEffect } from 'react';

const EMAILS = [
  {
    id: 1,
    from: 'HR Department <hr@nxterminal.corp>',
    subject: 'Welcome to NX Terminal Corp.',
    date: 'Mar 15, 1998',
    read: false,
    body: `Dear New Employee,

Welcome to NX Terminal Corp. Your workstation has been provisioned and your corporate ID has been generated.

Please note the following:
- Your probation period is indefinite
- Lunch breaks are 12 minutes (down from 15 due to "productivity optimization")
- The coffee machine on floor 3 is sentient. Do not make eye contact.
- Your salary of 200 $NXT/day will be deposited directly into your Protocol Wars account

The Protocol Wars simulation begins shortly. Your developers are your responsibility. Their failures are also your responsibility. Their successes belong to the corporation.

We look forward to your involuntary contributions.

Regards,
Human Resources (Ironic Name Division)
NX Terminal Corp.`,
  },
  {
    id: 2,
    from: 'IT Security <itsec@nxterminal.corp>',
    subject: 'URGENT: Password Policy Update',
    date: 'Mar 15, 1998',
    read: false,
    body: `ATTENTION ALL EMPLOYEES:

Effective immediately, all passwords must:
- Be at least 47 characters long
- Contain at least 3 ancient Sumerian symbols
- Include the exact air pressure at your desk (in hectopascals)
- Change every 4 hours
- Not be the same as any password ever used by anyone, anywhere, ever

Password hint questions have been replaced with existential dilemmas.

Failure to comply will result in your workstation being replaced with an Etch A Sketch.

- IT Security Team
  "We watch. Always."`,
  },
  {
    id: 3,
    from: 'CEO Office <ceo@nxterminal.corp>',
    subject: 'Re: Re: Re: Fwd: SYNERGY INITIATIVE Q2',
    date: 'Mar 14, 1998',
    read: true,
    body: `Team,

I am pleased to announce our new Synergy Initiative for Q2. After extensive consultation with our AI advisors (who we built, and who now tell us what to do), we have decided to:

1. Increase synergy by 200%
2. Leverage our core competencies to disrupt the disruption
3. Circle back on circling back
4. Action the action items from the action item meeting about action items

Remember: there is no "I" in "team", but there is an "I" in "termination".

Let's crush it (whatever "it" is).

- The CEO
  (Sent from my NX-486DX while stuck in the elevator)`,
  },
  {
    id: 4,
    from: 'Protocol Wars Admin <admin@protocolwars.nxt>',
    subject: 'Your Developers Await Orders',
    date: 'Mar 15, 1998',
    read: false,
    body: `Commander,

The Protocol Wars simulation is now live. Your developers have been initialized and are awaiting deployment.

Current Status:
- Simulation Year: 2005
- Active Corporations: 6
- Threat Level: MODERATE (will increase)
- Developer Morale: EXPENDABLE

Remember: In the Protocol Wars, there are no winners. Only survivors. And even they're not doing great.

Mint developers. Build protocols. Sabotage competitors. Try not to think about the ethical implications.

Good luck. You'll need it.

- Protocol Wars Automated Systems
  (This message was generated by AI. The AI regrets nothing.)`,
  },
  {
    id: 5,
    from: 'Facilities <facilities@nxterminal.corp>',
    subject: 'RE: Strange noises from Server Room B',
    date: 'Mar 13, 1998',
    read: true,
    body: `To whom it may concern,

Regarding your report about "strange noises" emanating from Server Room B:

After thorough investigation, we can confirm that the sounds are:
- NOT a ghost
- NOT the servers becoming sentient (again)
- NOT the intern we lost in there last quarter

It is simply the HVAC system. We think. We're 60% sure. Maybe 40%.

In any case, Server Room B has been reclassified from "Data Center" to "Do Not Enter Under Any Circumstances."

Thank you for your concern.

- Facilities Management
  "If it's not on fire, it's not our problem. If it IS on fire, it's still not our problem."`,
  },
];

export default function Inbox({ onUnreadCount }) {
  const [emails, setEmails] = useState(() => {
    const saved = localStorage.getItem('nx-inbox-read');
    if (saved) {
      const readIds = JSON.parse(saved);
      return EMAILS.map(e => ({ ...e, read: readIds.includes(e.id) }));
    }
    return EMAILS.map(e => ({ ...e }));
  });
  const [selectedId, setSelectedId] = useState(null);

  const unreadCount = emails.filter(e => !e.read).length;

  useEffect(() => {
    if (onUnreadCount) onUnreadCount(unreadCount);
  }, [unreadCount, onUnreadCount]);

  const handleSelect = (email) => {
    setSelectedId(email.id);
    if (!email.read) {
      const updated = emails.map(e => e.id === email.id ? { ...e, read: true } : e);
      setEmails(updated);
      const readIds = updated.filter(e => e.read).map(e => e.id);
      localStorage.setItem('nx-inbox-read', JSON.stringify(readIds));
    }
  };

  const selectedEmail = emails.find(e => e.id === selectedId);

  return (
    <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
      <div style={{
        padding: '4px 8px',
        background: 'var(--win-bg)',
        borderBottom: '1px solid var(--border-dark)',
        display: 'flex',
        alignItems: 'center',
        gap: '8px',
        fontSize: '11px',
      }}>
        <span style={{ fontWeight: 'bold' }}>NX Mail</span>
        <span style={{ color: '#666' }}>|</span>
        <span>{unreadCount} unread</span>
        {selectedEmail && (
          <>
            <span style={{ color: '#666' }}>|</span>
            <button
              className="win-btn"
              onClick={() => setSelectedId(null)}
              style={{ fontSize: '10px', padding: '1px 8px' }}
            >
              Back to Inbox
            </button>
          </>
        )}
      </div>

      {!selectedEmail ? (
        <div style={{ flex: 1, overflow: 'auto' }}>
          <table className="win-table" style={{ width: '100%' }}>
            <thead>
              <tr>
                <th style={{ width: '20px' }}></th>
                <th>From</th>
                <th>Subject</th>
                <th style={{ width: '100px' }}>Date</th>
              </tr>
            </thead>
            <tbody>
              {emails.map(email => (
                <tr
                  key={email.id}
                  className="clickable"
                  onClick={() => handleSelect(email)}
                  style={{ fontWeight: email.read ? 'normal' : 'bold' }}
                >
                  <td style={{ textAlign: 'center' }}>
                    {email.read ? '\u{1F4E8}' : '\u{1F4E9}'}
                  </td>
                  <td style={{ maxWidth: '180px', overflow: 'hidden', textOverflow: 'ellipsis' }}>
                    {email.from.split('<')[0].trim()}
                  </td>
                  <td>{email.subject}</td>
                  <td>{email.date}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      ) : (
        <div style={{ flex: 1, overflow: 'auto', padding: '8px' }}>
          <div style={{ marginBottom: '8px', paddingBottom: '8px', borderBottom: '1px solid var(--border-dark)' }}>
            <div style={{ fontWeight: 'bold', fontSize: '13px', marginBottom: '4px' }}>{selectedEmail.subject}</div>
            <div style={{ fontSize: '10px', color: '#444' }}>From: {selectedEmail.from}</div>
            <div style={{ fontSize: '10px', color: '#444' }}>Date: {selectedEmail.date}</div>
          </div>
          <pre style={{
            fontFamily: "'Tahoma', sans-serif",
            fontSize: '11px',
            whiteSpace: 'pre-wrap',
            lineHeight: 1.5,
          }}>
            {selectedEmail.body}
          </pre>
        </div>
      )}
    </div>
  );
}
