// config/gameConfig.js
export const SIMULATION_CONFIG = {
  MIN_DURATION_DAYS: 21,
  MAX_DEVS: 35000,
  YEARS_SIMULATED: 20,
  YEAR_CYCLE_HOURS: 12,
  SALARY_PER_DEV_PER_DAY: 200,
  MAX_ENERGY: 10,
  ENERGY_RECOVERY: 3,
  ENERGY_RECOVERY_HOURS: 4,
};
