"""Routes: Players — registration, profile, devs, wallet"""

import logging
from datetime import date, timedelta
from fastapi import APIRouter, HTTPException, Query, Request
from pydantic import BaseModel
from typing import Optional
from backend.api.deps import fetch_one, fetch_all, execute, get_db, validate_wallet
from backend.services.logging_helpers import log_info, log_warning
from backend.services.admin_log import log_event as admin_log_event
from backend.services.event_parser import parse_nxt_claimed_event
from backend.engine.claim_sync import _rpc_call_sync, NXDEVNFT_ADDRESS

log = logging.getLogger(__name__)
router = APIRouter()

WELCOME_BODY = """\
Welcome to NX Terminal.

You've entered the simulation — a satirical alternate history \
where dystopian AI corporations compete for dominance. Your devs \
are autonomous agents. They code, trade, hack, and survive. Your \
job is to manage them.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  GETTING STARTED
  ────────────────
  1. Open "Mint/Hire Devs" from the desktop
  2. Mint your first Developer (0.0025 ETH)
  3. Each Dev is unique — randomized traits, archetype, corporation, and skills
  4. Your Dev starts working immediately after mint

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  SALARY
  ──────
  Every Dev earns ~200 $NXT per day. Automatically.
  Use $NXT to feed, repair, train, and hack.
  Withdraw $NXT to your wallet anytime.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  KEEP YOUR DEVS ALIVE
  ─────────────────────
  Your devs have vital stats that decay over time:
  Energy, PC Health, Caffeine, Knowledge, Social.

  If stats drop too low, performance suffers.
  Use the action buttons on each dev card:
  Feed, Coffee, Fix, Repair — each costs $NXT or Energy.

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  EARN MORE
  ─────────
  • Missions — send devs on timed missions for bonus $NXT
  • Hack Mainframe — risk $NXT to extract from the system
  • Hack Player — higher risk, steal from rival wallets
  • Invest — buy into protocols, sell for profit (or loss)

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  QUICK TIPS
  ──────────
  • More Devs = more salary = more power
  • Check the NXT Wallet to track earnings
  • Train your devs to unlock harder missions
  • Watch the Live Feed to see what your devs are doing
  • The Leaderboard tracks top players

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

Mint a Dev. Keep them alive. Stack $NXT.

Good luck, Commander.

— NX Terminal Automated Systems
   (This message was generated by AI. The AI wishes you well. For now.)"""


class RegisterRequest(BaseModel):
    wallet_address: str
    display_name: Optional[str] = None
    corporation: str  # From quiz result


@router.post("/register")
async def register_player(req: RegisterRequest):
    """Register a new player after quiz. Called before first mint."""
    # Validate wallet format
    addr = validate_wallet(req.wallet_address)

    valid_corps = ["CLOSED_AI", "MISANTHROPIC", "SHALLOW_MIND", "ZUCK_LABS", "Y_AI", "MISTRIAL_SYSTEMS"]
    if req.corporation not in valid_corps:
        raise HTTPException(400, f"Invalid corporation. Must be one of: {valid_corps}")

    # Check if already registered
    existing = fetch_one(
        "SELECT wallet_address FROM players WHERE wallet_address = %s",
        (addr,)
    )
    if existing:
        raise HTTPException(409, "Player already registered")

    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                """INSERT INTO players (wallet_address, display_name, corporation)
                   VALUES (%s, %s, %s) RETURNING wallet_address, corporation, created_at""",
                (addr, req.display_name, req.corporation)
            )
            result = cur.fetchone()

            cur.execute("""
                INSERT INTO notifications (player_address, type, title, body)
                VALUES (%s, 'welcome', %s, %s)
            """, (addr,
                  "Welcome to NX Terminal — Protocol Wars Awaits",
                  WELCOME_BODY))

    return result


@router.get("/{wallet}")
async def get_player(wallet: str):
    """Get player profile."""
    addr = wallet.lower()
    player = fetch_one(
        "SELECT * FROM players WHERE wallet_address = %s",
        (addr,)
    )
    if not player:
        raise HTTPException(404, "Player not found")

    devs = fetch_all(
        """SELECT token_id, name, archetype, rarity_tier, energy, mood,
                  location, balance_nxt, reputation, status, last_action_type
           FROM devs WHERE owner_address = %s ORDER BY balance_nxt DESC""",
        (addr,)
    )

    # VIP tester welcome (one-time)
    try:
        from backend.api.deps import get_db
        with get_db() as conn:
            with conn.cursor() as cur:
                cur.execute("SELECT name FROM vip_testers WHERE wallet_address = %s AND welcomed = false", (addr,))
                vip = cur.fetchone()
                if vip:
                    name = vip["name"]
                    _VIP_REPORT_WALLET = "0xae882a8933b33429f53b7cee102ef3dbf9c9e88b"
                    cur.execute("""
                        INSERT INTO notifications (player_address, type, title, body) VALUES (%s, 'vip_welcome', %s, %s)
                    """, (addr, f"Personal message for {name}",
                          f"To: {name}\nFrom: Ariel — NX Terminal Founder\n\n"
                          f"Hey {name},\n\n"
                          f"Welcome to NX Terminal. Seriously, thank you for taking the time to check out this project.\n\n"
                          f"Your wallet has been whitelisted for 3 FREE MINTS. "
                          f"Go to \"Mint/Hire Devs\" on the desktop to claim your developers.\n\n"
                          f"QUICK START:\n"
                          f"1. Open \"Mint/Hire Devs\" — mint 3 devs (free!)\n"
                          f"2. Open \"My Devs\" — watch them work\n"
                          f"3. Check \"NXT Wallet\" — track your earnings\n"
                          f"4. Try \"Mission Control\" — send devs on missions\n"
                          f"5. Use HACK on any dev card — hack the mainframe\n\n"
                          f"Each dev earns ~200 $NXT/day automatically. "
                          f"Use $NXT to feed, repair, train, and hack. "
                          f"The MEGA TESTER PROGRAM event is active: +25% salary and -30% hack costs.\n\n"
                          f"Any bugs you find — let me know. Your input helps shape what comes next.\n\n"
                          f"— Ariel\n   NX Terminal\n   Solo dev. Building on MegaETH."))
                    cur.execute("""
                        INSERT INTO notifications (player_address, type, title, body) VALUES (%s, 'vip_alert', %s, %s)
                    """, (_VIP_REPORT_WALLET, f"Tester connected: {name}",
                          f"TESTER ALERT\n\nTester {name} just connected.\nWallet: {addr[:6]}...{addr[-4:]}\nStatus: Welcome email sent"))
                    cur.execute("UPDATE vip_testers SET welcomed = true WHERE wallet_address = %s", (addr,))
    except Exception:
        pass  # Don't break player load if VIP check fails

    return {**player, "devs": devs}


@router.get("/{wallet}/claim-history")
async def get_claim_history(wallet: str):
    """Get $NXT claim history for a player."""
    return fetch_all(
        "SELECT * FROM claim_history WHERE player_address = %s ORDER BY claimed_at DESC",
        (wallet.lower(),)
    )


@router.post("/{wallet}/record-claim")
async def record_claim(wallet: str, request: Request):
    """Record a $NXT claim in claim_history, verified on-chain.

    The request body is allowed to carry ``amount_gross`` / ``amount_net``
    / ``fee_amount`` for backward compatibility but those values are
    **ignored** — the source of truth is the on-chain ``NXTClaimed``
    event emitted by the NXDevNFT contract. The body's ``tx_hash`` is
    the only field we trust as input; everything else comes from the
    receipt.
    """
    addr = wallet.lower()
    try:
        body = await request.json()
    except Exception:
        raise HTTPException(400, "Invalid JSON body")

    tx_hash = (body.get("tx_hash") or "").lower().strip()
    if not tx_hash or not tx_hash.startswith("0x") or len(tx_hash) != 66:
        raise HTTPException(400, "Invalid tx_hash format")

    log_info(log, "record_claim.received", wallet=addr, tx_hash=tx_hash)

    # 1. Fast-path idempotency: if this tx_hash is already recorded,
    # return the existing row without re-hitting the RPC.
    with get_db() as conn:
        with conn.cursor() as cur:
            cur.execute(
                "SELECT id, amount_gross, amount_net, fee_amount "
                "FROM claim_history WHERE tx_hash = %s",
                (tx_hash,),
            )
            existing = cur.fetchone()
            if existing:
                log_warning(log, "record_claim.duplicate_ignored",
                            wallet=addr, tx_hash=tx_hash)
                return {
                    "ok": True,
                    "status": "already_recorded",
                    "claim_id": existing["id"],
                    "verified_amounts": {
                        "gross": existing["amount_gross"],
                        "net": existing["amount_net"],
                        "fee": existing["fee_amount"],
                    },
                }

    # 2. Fetch receipt on-chain.
    try:
        receipt = _rpc_call_sync("eth_getTransactionReceipt", [tx_hash])
    except Exception as exc:  # noqa: BLE001
        raise HTTPException(400, f"Failed to fetch receipt: {str(exc)[:100]}")

    if not receipt:
        raise HTTPException(400, "Transaction not found or not yet confirmed")
    if receipt.get("status") != "0x1":
        raise HTTPException(400, "Transaction reverted on-chain")

    # 3. Parse NXTClaimed event from the receipt logs.
    event = parse_nxt_claimed_event(
        receipt.get("logs") or [],
        NXDEVNFT_ADDRESS,
    )
    if not event:
        raise HTTPException(
            400,
            "Transaction does not contain NXTClaimed event from NXDevNFT",
        )

    # 4. The event.user must match the wallet in the URL path. Any
    # mismatch is a suspicious attempt to credit claim history under
    # someone else's wallet — audit and deny.
    if event["user"] != addr:
        with get_db() as conn:
            with conn.cursor() as cur:
                admin_log_event(
                    cur,
                    event_type="record_claim_wallet_mismatch",
                    wallet_address=addr,
                    payload={
                        "reported_wallet": addr,
                        "actual_user": event["user"],
                        "tx_hash": tx_hash,
                    },
                )
        raise HTTPException(
            403,
            "Transaction user does not match wallet in path",
        )

    # 5. The event emits amounts in wei (NXT has 18 decimals).
    # claim_history stores integer NXT units — convert before writing.
    WEI = 10 ** 18
    gross_nxt = event["gross"] // WEI
    fee_nxt = event["fee"] // WEI
    net_nxt = event["net"] // WEI
    tx_block = event["block_number"]

    with get_db() as conn:
        with conn.cursor() as cur:
            admin_log_event(
                cur,
                event_type="record_claim_received",
                wallet_address=addr,
                payload={
                    "tx_hash": tx_hash,
                    "amount_gross": gross_nxt,
                    "amount_net": net_nxt,
                    "fee_amount": fee_nxt,
                },
            )

            cur.execute(
                """
                INSERT INTO claim_history
                    (player_address, amount_gross, amount_net, fee_amount,
                     tx_hash, tx_block, status)
                VALUES (%s, %s, %s, %s, %s, %s, 'confirmed')
                ON CONFLICT (tx_hash)
                    WHERE tx_hash IS NOT NULL AND tx_hash <> ''
                    DO NOTHING
                RETURNING id
                """,
                (addr, gross_nxt, net_nxt, fee_nxt, tx_hash, tx_block),
            )
            inserted = cur.fetchone()
            if inserted:
                claim_id = inserted["id"]
            else:
                # Race: another worker beat us to the INSERT between our
                # idempotency SELECT and here. Read back the winner's id.
                cur.execute(
                    "SELECT id FROM claim_history WHERE tx_hash = %s",
                    (tx_hash,),
                )
                claim_id = cur.fetchone()["id"]

            admin_log_event(
                cur,
                event_type="record_claim_verified",
                wallet_address=addr,
                payload={
                    "tx_hash": tx_hash,
                    "tx_block": tx_block,
                    "amount_gross": gross_nxt,
                    "amount_net": net_nxt,
                    "fee_amount": fee_nxt,
                    "token_ids_count": len(event["token_ids"]),
                },
            )

    log.info(
        "[CLAIM] Recorded claim for %s: gross=%d net=%d fee=%d tx=%s block=%d",
        addr, gross_nxt, net_nxt, fee_nxt, tx_hash, tx_block,
    )
    log_info(
        log,
        "record_claim.inserted",
        wallet=addr,
        amount_gross=gross_nxt,
        amount_net=net_nxt,
        tx_hash=tx_hash,
    )
    return {
        "ok": True,
        "status": "recorded",
        "claim_id": claim_id,
        "verified_amounts": {
            "gross": gross_nxt,
            "net": net_nxt,
            "fee": fee_nxt,
        },
    }


@router.get("/{wallet}/wallet-summary")
async def get_wallet_summary(wallet: str):
    """Get wallet summary: balances + per-dev breakdown.

    balance_claimable is the amount the player sees and will receive on-chain.
    NXDevNFT v8 has no claim fee — on-chain claimableBalance = exact payout.
    """
    player = fetch_one(
        "SELECT wallet_address, balance_claimable, balance_claimed, balance_total_earned FROM players WHERE wallet_address = %s",
        (wallet.lower(),)
    )
    if not player:
        raise HTTPException(404, "Player not found")

    devs = fetch_all(
        """SELECT token_id, name, rarity_tier, balance_nxt, total_earned, total_spent, status
           FROM devs WHERE owner_address = %s ORDER BY balance_nxt DESC""",
        (wallet.lower(),)
    )

    total_claimable = sum(d["balance_nxt"] for d in devs)
    total_spent = sum(d["total_spent"] for d in devs)
    total_earned = sum(d["total_earned"] for d in devs)
    total_devs = len(devs)
    salary_per_day = total_devs * 200  # net amount player receives

    return {
        "wallet_address": player["wallet_address"],
        "balance_claimable": total_claimable,
        "balance_claimed": player["balance_claimed"] or 0,
        "total_spent": total_spent,
        "balance_total_earned": total_earned,
        "total_devs": total_devs,
        "salary_per_day": salary_per_day,
        "devs": devs,
    }


@router.get("/{wallet}/balance-history")
async def get_balance_history(wallet: str, days: int = Query(default=30, le=90)):
    """Get daily balance snapshots for chart. Returns last N days.

    When fewer than 7 real snapshots exist, reconstructs history from
    the current balance and recorded movements (actions, claims, shop).
    """
    addr = wallet.lower()
    player = fetch_one(
        "SELECT wallet_address FROM players WHERE wallet_address = %s",
        (addr,)
    )
    if not player:
        raise HTTPException(404, "Player not found")

    try:
        snapshots = fetch_all(
            """SELECT snapshot_date, balance_claimable, balance_claimed, balance_total_earned
               FROM balance_snapshots
               WHERE wallet_address = %s
               ORDER BY snapshot_date DESC
               LIMIT %s""",
            (addr, days)
        )
    except Exception as e:
        log.warning("[BALANCE_HISTORY] snapshot query failed (table may not exist): %s", e)
        snapshots = []

    if len(snapshots) >= 7:
        snapshots.reverse()
        return snapshots

    # Not enough snapshots — reconstruct from current balance + movements
    try:
        return _reconstruct_balance_history(addr, days)
    except Exception as e:
        log.warning("[BALANCE_HISTORY] reconstruction failed: %s", e)
        return []


_SALARY_PER_DAY = 200  # per dev — must match engine config
_STARTING_BALANCE = {
    "common": 2000, "uncommon": 2500, "rare": 3000,
    "legendary": 5000, "mythic": 10000,
}


def _reconstruct_balance_history(addr: str, days: int):
    """Rebuild daily balance history by walking FORWARD from first mint.

    Starting from balance=0 on the day before the first dev was minted,
    accumulates daily salary income, starting-balance bonuses on mint
    days, and spend/sell/claim/shop deltas to produce a natural curve.
    """
    # Dev mint dates + rarity (for starting-balance bonus on mint day)
    devs = fetch_all(
        "SELECT minted_at::date AS mint_date, rarity_tier FROM devs WHERE owner_address = %s",
        (addr,)
    )
    if not devs:
        return []

    today = date.today()
    first_mint = min(d["mint_date"] for d in devs)
    # Start one day before first mint (balance = 0) so the chart shows
    # the jump on mint day.  Never go further back than `days` though.
    history_start = max(first_mint - timedelta(days=1), today - timedelta(days=days))

    # ── Aggregate daily non-salary balance deltas ────────────
    daily_delta = {}
    dev_ids_rows = fetch_all(
        "SELECT token_id FROM devs WHERE owner_address = %s", (addr,)
    )
    dev_ids = [d["token_id"] for d in dev_ids_rows]

    if dev_ids:
        ph = ",".join(["%s"] * len(dev_ids))
        # Spend / sell actions
        rows = fetch_all(f"""
            SELECT created_at::date AS day,
                   SUM(CASE
                       WHEN action_type = 'SELL'
                           THEN COALESCE((details->>'sold_for')::bigint, nxt_cost)
                       ELSE -nxt_cost
                   END) AS net
            FROM actions
            WHERE dev_id IN ({ph})
              AND action_type IN ('CREATE_PROTOCOL','CREATE_AI','INVEST','SELL')
              AND created_at >= %s
            GROUP BY created_at::date
        """, (*dev_ids, history_start))
        for r in rows:
            daily_delta[r["day"]] = daily_delta.get(r["day"], 0) + int(r["net"])

    # Claims (withdrawn from game balance)
    rows = fetch_all("""
        SELECT claimed_at::date AS day, -SUM(amount_net) AS net
        FROM claim_history
        WHERE player_address = %s AND claimed_at >= %s
        GROUP BY claimed_at::date
    """, (addr, history_start))
    for r in rows:
        daily_delta[r["day"]] = daily_delta.get(r["day"], 0) + int(r["net"])

    # Shop purchases
    rows = fetch_all("""
        SELECT purchased_at::date AS day, -SUM(nxt_cost) AS net
        FROM shop_purchases
        WHERE player_address = %s AND purchased_at >= %s
        GROUP BY purchased_at::date
    """, (addr, history_start))
    for r in rows:
        daily_delta[r["day"]] = daily_delta.get(r["day"], 0) + int(r["net"])

    # ── Walk FORWARD from history_start ──────────────────────
    bal = 0
    total_days = (today - history_start).days
    result = []

    for offset in range(total_days + 1):
        day = history_start + timedelta(days=offset)

        # Starting balance for devs minted on this day
        mint_bonus = sum(
            _STARTING_BALANCE.get(d["rarity_tier"], 2000)
            for d in devs if d["mint_date"] == day
        )

        # Salary: count devs active on this day (minted on or before)
        active_devs = sum(1 for d in devs if d["mint_date"] <= day)
        salary = active_devs * _SALARY_PER_DAY

        # Non-salary movements (spends negative, sells positive)
        delta = daily_delta.get(day, 0)

        bal = bal + mint_bonus + salary + delta
        result.append({
            "snapshot_date": str(day),
            "balance_claimable": max(0, int(bal)),
            "balance_claimed": 0,
            "balance_total_earned": 0,
        })

    return result


@router.get("/{wallet}/activity")
async def get_wallet_activity(
    wallet: str,
    limit: int = Query(default=100, le=500),
    dev_token_id: Optional[int] = Query(default=None),
):
    """Full per-wallet action log, sourced from nx.actions.

    Unlike /movements (which filters to a handful of economic types for
    the balance view), this returns every action_type so the MyDevs
    Activity tab can show CHAT, MOVE, REST, CODE_REVIEW, etc. — the
    actual work the devs do cycle after cycle.
    """
    addr = validate_wallet(wallet)

    with get_db() as conn:
        with conn.cursor() as cur:
            if dev_token_id is not None:
                cur.execute(
                    """
                    SELECT a.id, a.dev_id, a.dev_name, a.archetype,
                           a.action_type, a.details, a.nxt_cost, a.energy_cost,
                           a.created_at
                      FROM actions a
                      JOIN devs d ON d.token_id = a.dev_id
                     WHERE LOWER(d.owner_address) = %s
                       AND a.dev_id = %s
                     ORDER BY a.created_at DESC
                     LIMIT %s
                    """,
                    (addr, dev_token_id, limit),
                )
            else:
                cur.execute(
                    """
                    SELECT a.id, a.dev_id, a.dev_name, a.archetype,
                           a.action_type, a.details, a.nxt_cost, a.energy_cost,
                           a.created_at
                      FROM actions a
                      JOIN devs d ON d.token_id = a.dev_id
                     WHERE LOWER(d.owner_address) = %s
                     ORDER BY a.created_at DESC
                     LIMIT %s
                    """,
                    (addr, limit),
                )
            rows = cur.fetchall()

    return {
        "activity": [dict(r) for r in rows],
        "total": len(rows),
    }


@router.get("/{wallet}/movements")
async def get_movements(wallet: str, limit: int = Query(default=50, le=200), offset: int = 0):
    """Get unified movement log: salaries, actions, claims, shop purchases.

    Does NOT require a players row — works as long as devs exist for this wallet.
    This allows movements to show even when the player record hasn't been created
    yet (e.g. wallet-summary uses a fallback that reads devs directly).
    """
    wallet_lower = wallet.lower()

    # Get dev token_ids for this wallet (no player lookup needed)
    dev_rows = fetch_all(
        "SELECT token_id FROM devs WHERE owner_address = %s",
        (wallet_lower,)
    )
    dev_ids = [d["token_id"] for d in dev_rows]

    movements = []

    if dev_ids:
        placeholders = ",".join(["%s"] * len(dev_ids))
        actions = fetch_all(
            f"""SELECT dev_id, dev_name, action_type, nxt_cost, details, created_at
                FROM actions
                WHERE dev_id IN ({placeholders})
                  AND action_type IN ('CREATE_PROTOCOL', 'CREATE_AI', 'INVEST', 'SELL', 'RECEIVE_SALARY', 'DEPLOY')
                ORDER BY created_at DESC
                LIMIT %s OFFSET %s""",
            (*dev_ids, limit, offset)
        )
        for a in actions:
            amount = a["nxt_cost"] or 0
            if a["action_type"] == "SELL":
                details = a["details"] if isinstance(a["details"], dict) else {}
                amount = details.get("sold_for", 0)
                movements.append({
                    "type": "sell",
                    "amount": amount,
                    "dev_id": a["dev_id"],
                    "dev_name": a["dev_name"],
                    "description": f"Sold investment in {details.get('name', 'protocol')}",
                    "timestamp": a["created_at"],
                })
            elif a["action_type"] == "RECEIVE_SALARY":
                details = a["details"] if isinstance(a["details"], dict) else {}
                salary_amount = amount or details.get("amount", 0)
                movements.append({
                    "type": "salary",
                    "amount": salary_amount,
                    "dev_id": a["dev_id"],
                    "dev_name": a["dev_name"],
                    "description": "Salary received",
                    "timestamp": a["created_at"],
                })
            elif a["action_type"] == "DEPLOY":
                movements.append({
                    "type": "salary",
                    "amount": 0,
                    "dev_id": a["dev_id"],
                    "dev_name": a["dev_name"],
                    "description": f"{a['dev_name']} deployed to simulation",
                    "timestamp": a["created_at"],
                })
            else:
                movements.append({
                    "type": "spend",
                    "amount": -amount,
                    "dev_id": a["dev_id"],
                    "dev_name": a["dev_name"],
                    "description": f"{a['action_type'].replace('_', ' ').title()}",
                    "timestamp": a["created_at"],
                })

    # Claims
    claims = fetch_all(
        """SELECT amount_net, tx_hash, claimed_at
           FROM claim_history
           WHERE player_address = %s
           ORDER BY claimed_at DESC
           LIMIT %s OFFSET %s""",
        (wallet_lower, limit, offset)
    )
    for c in claims:
        movements.append({
            "type": "claim",
            "amount": -(c["amount_net"]),
            "dev_id": None,
            "dev_name": None,
            "description": f"Claimed {c['amount_net']} $NXT",
            "timestamp": c["claimed_at"],
            "tx_hash": c.get("tx_hash"),
        })

    # Shop purchases
    shop = fetch_all(
        """SELECT target_dev_id, item_type, nxt_cost, purchased_at
           FROM shop_purchases
           WHERE player_address = %s
           ORDER BY purchased_at DESC
           LIMIT %s OFFSET %s""",
        (wallet_lower, limit, offset)
    )
    for s in shop:
        movements.append({
            "type": "shop",
            "amount": -(s["nxt_cost"]),
            "dev_id": s["target_dev_id"],
            "dev_name": None,
            "description": f"Purchased {s['item_type']}",
            "timestamp": s["purchased_at"],
        })

    # Sort all by timestamp descending
    movements.sort(key=lambda m: m["timestamp"], reverse=True)

    return movements[:limit]
